-- Jenkins Metadata

CREATE TABLE IF NOT EXISTS BUILD_MASTER (
	JOB_NAME_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	JOB_NAME varchar(60) UNIQUE
);

CREATE TABLE IF NOT EXISTS HOST_MASTER (
	HOST_NAME_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	HOST_NAME varchar(40) UNIQUE
);

-- Mapping table of the above two
CREATE TABLE IF NOT EXISTS BUILD_HOST_MAP (
	JOB_ID INT,
	HOST_ID INT,
	PRIMARY KEY (JOB_ID, HOST_ID),
	CONSTRAINT JOB_FK FOREIGN KEY (JOB_ID) REFERENCES BUILD_MASTER (JOB_NAME_ID),
  	CONSTRAINT HOST_FK FOREIGN KEY (HOST_ID) REFERENCES HOST_MASTER (HOST_NAME_ID)
);

-- Build Info for last successful Build
CREATE TABLE IF NOT EXISTS LAST_SUCCESSFUL_BUILD (
	JOB_NAME varchar(40),
	HOST_NAME varchar(40),
	BUILD_NUMBER INT,
	BUILD_INFO_JSON varchar(100),
	PRIMARY KEY (JOB_NAME, HOST_NAME)
);

