USE quartz;

-- Jenkins Metadata

CREATE TABLE BUILD_MASTER (
	JOB_NAME_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	JOB_NAME varchar(40) UNIQUE
);

CREATE TABLE HOST_MASTER (
	HOST_NAME_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	HOST_NAME varchar(40) UNIQUE
);

-- Mapping table of the above two
CREATE TABLE BUILD_HOST_MAP (
	JOB_ID INT,
	HOST_ID INT,
	PRIMARY KEY (JOB_ID, HOST_ID),
	CONSTRAINT JOB_FK FOREIGN KEY (JOB_ID) REFERENCES BUILD_MASTER (JOB_NAME_ID),
  	CONSTRAINT HOST_FK FOREIGN KEY (HOST_ID) REFERENCES HOST_MASTER (HOST_NAME_ID)
);
