ALTER TABLE AUTHORITY_TAG_MAP MODIFY LDAP_AUTH_NAMES varchar(500); 

CREATE TABLE IF NOT EXISTS AWS_BILL_FILE_INFO (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BILL_FILE varchar(200) NOT NULL UNIQUE
)

CREATE TABLE IF NOT EXISTS AWS_CPU_THRESHOLD (
	THRESHOLD_META_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	INSTANCE_ID INT,
	THRESHOLD_CPU_DAILY INT,
	SKIP_ME_FLAG TINYINT(1),
	UNIQUE KEY AWS_CPU_THRESHOLD_KEY (INSTANCE_ID,THRESHOLD_CPU_DAILY),
	CONSTRAINT INST_CPU_THRESHOLD_FK FOREIGN KEY (INSTANCE_ID) REFERENCES INSTANCE_MASTER (ID)
);