ALTER TABLE AUTHORITY_TAG_MAP MODIFY LDAP_AUTH_NAMES varchar(500); 

CREATE TABLE IF NOT EXISTS AWS_BILL_FILE_INFO (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BILL_FILE varchar(200) NOT NULL UNIQUE
)
