CREATE TABLE LDAP_AUTHORITY_MASTER (
	LDAP_AUTH_ID TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	LDAP_AUTH_NAME varchar(40)
);

CREATE TABLE APP_AUTHORITY_MASTER (
	APP_AUTH_ID TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	APP_AUTH_NAME varchar(40)
);

CREATE TABLE AUTHORITY_MAP (
	LDAP_AUTHORITY_ID TINYINT,
	APP_AUTHORITY_ID TINYINT,
	PRIMARY KEY (LDAP_AUTHORITY_ID, APP_AUTHORITY_ID),
	CONSTRAINT APP_FK FOREIGN KEY (APP_AUTHORITY_ID) REFERENCES APP_AUTHORITY_MASTER (APP_AUTH_ID),
  	CONSTRAINT LDAP_FK FOREIGN KEY (LDAP_AUTHORITY_ID) REFERENCES LDAP_AUTHORITY_MASTER (LDAP_AUTH_ID)
);

-- Access Condition Mapper

CREATE TABLE AUTHORITY_TAG_MAP (
	TAG_TYPE varchar(40), 
	TAG_VALUE varchar(40),
	LDAP_AUTH_NAMES varchar(40),
	PRIMARY KEY (TAG_TYPE, TAG_VALUE)
);

-- Audit 

CREATE TABLE AUDIT_INFO (
	AUDIT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	EVENT_TYPE varchar(80),
    EVENT_PARAMS varchar(80),
    USER varchar(40),
    EVENT_TIME datetime
);

-- data 

insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) value ('techops');
insert into APP_AUTHORITY_MASTER(APP_AUTH_NAME) value ('Operator');
insert into APP_AUTHORITY_MASTER(APP_AUTH_NAME) value ('Administrator');
insert into APP_AUTHORITY_MASTER(APP_AUTH_NAME) value ('Manager');
insert into AUTHORITY_MAP value (1,1);
insert into AUTHORITY_MAP value (1,2);
insert into AUTHORITY_MAP value (1,3);


-- techops-int entries
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) value ('techops-int');
insert into AUTHORITY_MAP value (2,1);
insert into AUTHORITY_MAP value (2,2);
insert into AUTHORITY_MAP value (2,3);

insert into AUTHORITY_TAG_MAP(TAG_TYPE,TAG_VALUE,LDAP_AUTH_NAMES) value ('cost-center','CP','techops,Ops');
insert into AUTHORITY_TAG_MAP(TAG_TYPE,TAG_VALUE,LDAP_AUTH_NAMES) value ('stack','qa','techops,Ops,qa-all');
insert into AUTHORITY_TAG_MAP(TAG_TYPE,TAG_VALUE,LDAP_AUTH_NAMES) value ('stack','dev','techops,Ops,dev-all');
