-- data 
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Accessibility Testing Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Account Payable');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Account Receivable');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Accounting');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Admin Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Advance Health');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Advance Health Dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Advance Health QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Advance Health Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Aetna');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Aetna-Dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Aetna-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ahim-impl-carrier-support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('AHIM-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('AHIM-QA-INDIA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('AHIM-Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('AHIM Vendor Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ahim.support@hcentive.com');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Alive hCentive');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('all');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-hcentive');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-LittleRock');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-LittleRock-Contractors');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-LittleRock-Employees');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-Noida');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-Noida-Contractors');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-Noida-Employees');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-Noida-visitors');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('all-qa');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-Reston');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-Reston-Contractors');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-Reston-Employees');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-US-contractors');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('all-us-employees');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-US-Managers');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-US-Remote');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All-US-visitors');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('All Managers');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ALL QA US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Alliant');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Alliant-dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Alliant-qa');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('alliant-team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Alliant production email bounces');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Alliant production email complaints');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Alliant Production Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Application Security Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Applications at Webinsurebenefits');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('appscan');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('AR-HIX-ALL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('AR-Prodsupport');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Arkansas-SIT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Arkansas-uat');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Arkansas Prod');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ARSHOP Release Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Automation-qa-leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('aws-advancehealth');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('aws-alliant-dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('aws-co-hix');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('aws-deltadental-dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('aws-ma-hix');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('aws-prod');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('aws-sparrow-prod');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('aws-wem');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('aws-xpg-prod');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('AWS Medicare');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('AWS Product Demo');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('b2b sales');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('billing-ba');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Billing-External');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('billing-team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Billing Dev team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Billing Product');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Billing QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Billing Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Billing UI');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Blueheeler Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Buddy Connect');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('build');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Career India');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Career US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CEO External Account');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CGI CO');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CGI KY');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CMS-DE');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CMS/SBE-EDI Issues');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CO-HIX QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CO HIX');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Coding Gems');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('COHIX Offshore');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Compliance');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Connect Admin');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('connectHR');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('contactus');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Contractor Payments');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Coventry');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Coventry-Dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Coventry-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Coventry eTool');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Coventry Medicare');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CP-Admin');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CP-Prodsupport');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CP-WIG-Admin');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CP-WIG-UAT-Admin');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CP_Mgt');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CSC NY');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CSRGroup');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Customer Care');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('cvty-external-notify');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('cvty-internal-notify');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('cvty-support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('CVTY_ERR_RPT_TST');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('dd-production-notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('DDIL-Production-Notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('DDWI-CVH-HN-QA-Grp');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('delta');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Delta-Dental');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Delta Dental');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Dinoct');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Direct Enrollment');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Direct Enrollment - Development');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('drprod');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Ebill Production Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ETOOL-QA-Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('EXM-QA Implementation');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('FFM Shop O&M');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('FFMShop-ALL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ffmshop-perf');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('FFMSHOP AFS QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ffmshop ba');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ffmshop dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ffmshop managers');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ffmshop qa');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('FFMSHOP_REL_TEAM');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('FHM-Prodsupport');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('FHM-Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ghp-production-notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('government.solutions@hcentive.com');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('gs');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HA-PHIX-DEV');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HA-PHIX-DEV-LEAD');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HA-PHIX-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HA-PHIX-Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HA-PHIX-Tech');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HA-PHIX-US-TEAM');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ha-production-notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HA-TS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HA PHIX BA Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HAP-Dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HAP-Offshore');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HC-WLP-PROD-SUPPORT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hc-wlp-support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HC-WLP-TEST-SUPPORT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hCentive-BA-Forum');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Hcentive Backgroundcheck');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hCentive CEO');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hCentive Corporate Office');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hCentive Cricket Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hCentive HIX : Product Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hCentive Product Architecture');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hCentive Proposal & Technical Writers Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hCentive Public Exchange User Group');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hcentive sales : technical Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Health Alliance');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Health Net Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('healthnet CA Pinnacle');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HELLO');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Hiring');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Hiring Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-ALL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-BA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-DEV');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-INDIA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-Leadership');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-LEADS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-PMIND');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-PMSHOP');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-PROD-MGT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-PROD-STAFF-BR');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-RDTI');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-RDTS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-SHOP-Prd-Mgt');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX-US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX Management');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX Product Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX QA Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX SHOP Dexter');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX SHOP Lannister');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX SHOP LEADS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX SHOP Managers');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX SHOP Mavericks');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HIX SHOP PROD MGT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HN-hC-Status');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hn-production-notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HN CTS mailing list');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hnproject');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HR-US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('HR Confidential');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hr@hcentive.com');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('hrvendor');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Human Resources');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('I Learn');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ICC');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('idm-prodsupport');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ImplDeltaDental');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Incidents');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('incoming faxes');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Info - Webinsure');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Information Security Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('infra-noc');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Infra-Vendors');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Infrastucture');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('iOS Developers');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('IS Builds');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Issue Collector');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('IT-Apple');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('IT and Security Updates');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('IT Desk OPS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('IT India');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('IT Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('IT US group');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ITL-ALL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('itl-notifications');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ITL-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ITNETOPS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ITUNIXOPS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ITWINOPS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('jack.esselen@gmail.com');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('jaspersoft');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('jira');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ky-offshore-team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('KY HIX');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ky QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Leadership');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Leadership Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Liason Account for External Partners for Developent');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('licensing and appointments');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('MA-HIX-ALL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('MA-HIX-BA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('MA-HIX-DEV');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ma-hix-leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('MA-HIX-OANDM');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('MA-HIX-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('MA Offshore Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Managers India');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Managers US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Marketing Department');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Marketing External');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('MAS HIX');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Media');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Medicare-BA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('medicare-product-team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Medicare Development');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Medicare Development leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Medicare Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Medicare Team SPOCs');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Mock-Enrollment-Customer-Service@hcentive.com');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Mock-Enrollment-Participants@hcentive.com');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('NETSUITE-IMPL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ngs-all@hcentive.com');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Noida-R&D1');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Noida-R&D2');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('NY HIX');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Offshore PS Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Onsite Managers');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Onsite Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('p.mccain');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Payroll Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PBEX-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('performance-engineering');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PERX-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PGP encryption');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix-ba-team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix-Demo-Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix-Dev-Leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix-Dev-Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('phix-fid-qa');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX-GHP-TS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix-Golive');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('phix-group1');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX-HA-TS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX-HAP team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX-IMPL-BA-Offshore');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('phix-impl-plan-mgmt');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX-Internal-Stakeholders');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX-L4_Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix-Product-Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('phix-team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX-Wellcare');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX BA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX CP QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix Demo Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX Fidelity-Implementation');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX GHP');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX HAP QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('phix impl dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX Impls');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix Integration Automation');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX internal');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX NFR Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX QA Leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX QA Team5');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix Scrum Leaders');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Phix Scrum Masters');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PHIX Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PMS-HA Implementation Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Procurement');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('product-team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Product Demo Email Sending Account');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Product Management team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Production Servers');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('psteam internal useonly');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('public-dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('public-hix-leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Public Exchange');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('PUDG');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('QA-LT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('QA-LTE');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('QA-Managers');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('QA Automation');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('QA shared services team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Quarterone_india_appraisal');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('redhat');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Refer Hcentive');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Refer India');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Refer US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Resource Management Group');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Reston Corporate Office Visitors');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('RMHP-INDIA-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('rmhp-production-notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('RMHP-SHP-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('RMHP-TS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Sales - WebInsure');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Sev 1 Alert');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Sev 1 War Room');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Sev 2 Advisory');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Sev 2 War Room');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('SEV1');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('sev2');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Shared Services Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('shp-production-notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('si-public-exchange');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('sit-mail-notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Softwares');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('splunk-arshop');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-etools');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('splunk-noc');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-Phix');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-Phix-CP');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-Phix-Fidelity');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-Phix-GHP');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-Phix-HA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-Phix-Wellcare');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('splunk-prod-support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('splunk-security-team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-sso');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('splunk-techops');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-wfm');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Splunk-wig');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('SSO DL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('ssoteam');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('state-exchange-roundup');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Support - WebInsure');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('techops');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Tennis');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('tglica-production-notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Timesheet Management');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Training');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Travel desk Noida');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Uber User Group');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('uhg-production-notification');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('US-OPS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('us-support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('US Architects');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('US Front Desk');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('US Operator Voicemail');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('US Travel');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('USTravelDesk');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Vulnerability Management Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WebInsure Customer Service');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WebInsureBen');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('website');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Wellcare-Admin');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Wellcare-Wig-Admin');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-ALL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-ARCHITECTURE');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-BA-Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-CONFIG');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-CVTY');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-DDIL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-DDWI');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-EDI');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-FUNCTIONAL-BA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-FUNCTIONAL-ENRL-BA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-GHP');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-GUESTS');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-HA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-HN');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-imp-deliveryLT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-imp-deployment');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-imp-edi');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-HN');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-IN');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-IN-BA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-IN-DEV');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-IN-QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-US-BA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-US-PM');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-US-SA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMP-WKL');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-Impl-Leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IMPL-QA-Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-IN');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-Integration');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-LT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-LTE');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-noida');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-product-dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-PRODUCTION-SUPPORT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-qa');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-qa-leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-RMHP');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-SECURITY-CONTACT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-ServicesTeam');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-SHP');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-TECHNICAL-CONTACT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-TGLICA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-UHG');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-uhg-testfiles');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wem-ui-team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-US-BAs');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM-WELLPOINT');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM BPM Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM Build Mgmt Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM Dev Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM Engg Leads');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Wem ffm Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM Product Support (Internal)');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM Support US');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM Value Prop');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Wem Wig Dev');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Wem Wig Qa');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEM Wig Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WEMP-IMP-DEV');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wemtesting');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WFM-Prodsupport');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wfm rmhp impl');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('wi-support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WIC Review Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Wig-L4-Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Wig-Prodsupport');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WIG-Support');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Wig-Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WIG QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WII-Team');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WLP DEV');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WLP Offshore');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('WLP QA');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Women\'s Group');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('Writes leaders');
insert into LDAP_AUTHORITY_MASTER(LDAP_AUTH_NAME) values('XPG-HA-TS');

insert into APP_AUTHORITY_MASTER(APP_AUTH_NAME) value ('Operator');
insert into APP_AUTHORITY_MASTER(APP_AUTH_NAME) value ('Administrator');
insert into APP_AUTHORITY_MASTER(APP_AUTH_NAME) value ('Manager');

-- sample data
-- insert into AUTHORITY_MAP value (<LDAP_AUTH_NAME of value techops>,<APP_AUTH_ID of value Administrator>);

insert into AUTHORITY_TAG_MAP(TAG_TYPE,TAG_VALUE,LDAP_AUTH_NAMES) value ('Cost-Center','phix','techops');
insert into AUTHORITY_TAG_MAP(TAG_TYPE,TAG_VALUE,LDAP_AUTH_NAMES) value ('Stack','qa','techops');
insert into AUTHORITY_TAG_MAP(TAG_TYPE,TAG_VALUE,LDAP_AUTH_NAMES) value ('Stack','dev','techops,Ops');

